use AULAS_NOITE_2019;
CREATE TABLE ENDERECO(
COD_END INT,
 RUA CHAR(50),
 NUM INT,
 CIDADE CHAR(30),
 PRIMARY KEY(COD_END)
);

DESCRIBE ENDERECO;
INSERT INTO ENDERECO VALUES (100, 'BARAÙNAS', 30, 'SÃO PAULO'),
(200, 'MOOCA', 452, 'SÃO PAULO'),
 (300, 'FARIAS', 333, 'SÃO PAULO'),
 (400, 'AV PRAIA', 597, 'SANTOS'),
 (500, 'LEBLON', 1003, 'RIO DE JANEIRO');

SELECT * FROM ENDERECO;
ALTER TABLE TIMES
ADD COLUMN UF CHAR(2),
 ADD COLUMN COD INT,
 ADD COLUMN COD_END INT,
 ADD PRIMARY KEY(UF, COD);
 -- OUTRAS CHAMADAS PARA ADD PK FALHAM NO MARIADB.
 -- NAO DEVE HAVER NENHUMA PK ANTES DE ADICIONAR, E TODAS DEVEM SER
ADICIONADAS EM UMA UNICA CHAMADA.

DESCRIBE TIMES;
SET SQL_SAFE_UPDATES=0;
UPDATE TIMES SET
UF='SP', COD=50, COD_END=100
WHERE NOME='CORINTHIANS';

UPDATE TIMES SET
UF='SP', COD=60, COD_END=200
WHERE NOME='PALMEIRAS';

UPDATE TIMES SET
UF='SP', COD=70, COD_END=300
WHERE NOME='SAO PAULO';
UPDATE TIMES SET
UF='SP', COD=80, COD_END=400
WHERE NOME='SANTOS';
UPDATE TIMES SET
UF='RJ', COD=90, COD_END=500
WHERE NOME='FLAMENGO';

SELECT * FROM TIMES;
