USE AULAS_NOITE_2019;

CREATE TABLE DEPARTAMENTO(
	CODDEPTO INT PRIMARY KEY,
	NOME VARCHAR(30)
);

CREATE TABLE PROFESSOR(
	MAT INT PRIMARY KEY,
	NOME VARCHAR(30),
	CODDEPTO INT,
	FOREIGN KEY (CODDEPTO)  -- chave estrangeira nesta tabela
	REFERENCES DEPARTAMENTO(CODDEPTO)  -- aponta pra chave primaria de outra tabela
	ON DELETE SET NULL  -- quando deletar, muda pra NULL
);

INSERT INTO DEPARTAMENTO VALUES
	(1, 'COMPUTACAO'),
	(2, 'MATEMATICA'),
	(3, 'BIOLOGIA'),
	(4, 'ESTATISTICA');

INSERT INTO PROFESSOR VALUES
	(111, 'VLADIMIR', 1),
	(214, 'SABRINA', 1),
	(333, 'GIL', 4),
	(450, 'MAURICIO', 3);

DELETE FROM DEPARTAMENTO WHERE CODDEPTO = 1;

CREATE VIEW PROFV AS
	SELECT NOME
	FROM PROFESSOR;

SELECT * FROM PROFV;
