USE AULAS_NOITE_2019;

CREATE TABLE AMD(DATA_T DATE, ABERTURA FLOAT,
  ALTA FLOAT,
  FECHAMENTO FLOAT,
  FECHAMENTO_AJUSTADO FLOAT,
  VOLUME INT);
  
LOAD DATA LOCAL INFILE 'AMD-stock.csv'
  INTO TABLE AMD
  FIELDS TERMINATED BY ','
  ENCLOSED BY '"'
  LINES TERMINATED BY '\n'
  IGNORE 1 ROWS;

SELECT MAX(FECHAMENTO) FROM AMD;

SELECT MIN(FECHAMENTO) FROM AMD;

SELECT AVG(FECHAMENTO) FROM AMD;

SELECT FORMAT(AVG(FECHAMENTO),2) FROM AMD;

SELECT FORMAT(SUM(FECHAMENTO),2) FROM AMD;

SELECT FORMAT(100*SUM(FECHAMENTO),2) FROM AMD;

SELECT COUNT(*) FROM AMD;

SELECT MIN(DATA_T) FROM AMD;

SELECT MAX(DATA_T) FROM AMD;

SELECT * FROM AMD WHERE DATA_T BETWEEN '1990-01-01' AND '2018-01-01'

LIMIT 10;

SELECT MAX(FECHAMENTO), MIN(FECHAMENTO), AVG(FECHAMENTO) FROM AMD

WHERE DATA_T BETWEEN '1990-01-01' AND '2018-01-01';
